USE master
GO

ALTER DATABASE QuanLyCuaHang SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE IF EXISTS QuanLyCuaHang
GO

CREATE DATABASE QuanLyCuaHang
GO

USE QuanLyCuaHang
GO

-- Tạo bảng CUAHANG
CREATE TABLE CUAHANG (
    mach CHAR(10) PRIMARY KEY,   -- Mã cửa hàng (Khóa chính)
    tench NVARCHAR(20) NOT NULL,           -- Tên cửa hàng
    diachi NVARCHAR (100) NOT NULL, 
	hotline VARCHAR (10) NOT NULL,
	email VARCHAR (50) NOT NULL
);

-- Tạo bảng NHACUNGCAP
CREATE TABLE THUONGHIEU (
    math CHAR(10) PRIMARY KEY, -- Mã nhà cung cấp (Khóa chính)
    tenth NVARCHAR(20) NOT NULL,          -- Tên nhà cung cấp
   
);


-- Tạo bảng LOAISANPHAM
CREATE TABLE LOAISANPHAM (
    maloai CHAR(10) PRIMARY KEY,
    tenloai NVARCHAR(11) NOT NULL,
);

-- Tạo bảng CHATLIEU
CREATE TABLE CHATLIEU (
    macl CHAR(10) PRIMARY KEY,
    tencl NVARCHAR(10) NOT NULL,
    dactinh NVARCHAR(50)
);

-- Tạo bảng SANPHAM
CREATE TABLE SANPHAM (
    masp CHAR(10) PRIMARY KEY, 
    tensp NVARCHAR(50) NOT NULL,
    maloai CHAR(10) NOT NULL, --FK LOAISANPHAM
    math CHAR(10) NOT NULL,	 --FK THUONGHIEU
	macl CHAR(10) NOT NULL,	 --FK CHATLIEU
	gianhap FLOAT NOT NULL,
    giaban FLOAT NOT NULL
);

ALTER TABLE dbo.SANPHAM ADD CONSTRAINT FK_LOAISANPHAM FOREIGN KEY (maloai) REFERENCES LOAISANPHAM(maloai)
ALTER TABLE dbo.SANPHAM ADD CONSTRAINT FK_THUONGHIEU FOREIGN KEY (math) REFERENCES THUONGHIEU(math)
ALTER TABLE dbo.SANPHAM ADD CONSTRAINT FK_CHATLIEU FOREIGN KEY (macl) REFERENCES CHATLIEU(macl)

-- Tạo bảng SIZE
CREATE TABLE SIZE (
    masize CHAR(10) PRIMARY KEY,
    tensize NVARCHAR(10) NOT NULL
);

-- Tạo bảng SIZE
CREATE TABLE TONKHO (
	mach CHAR(10) NOT NULL,   --FK TONKHO_CUAHANG
    masp CHAR(10) NOT NULL,   --FK SANPHAM
	masize CHAR(10) NOT NULL, --FK SIZE
	soluong int  NOT NULL,
	PRIMARY KEY (mach, masp, masize)
);

ALTER TABLE dbo.TONKHO ADD CONSTRAINT FK_TONKHO_SANPHAM FOREIGN KEY (masp) REFERENCES dbo.SANPHAM(masp)
ALTER TABLE dbo.TONKHO ADD CONSTRAINT FK_TONKHO_SIZE FOREIGN KEY (masize) REFERENCES dbo.SIZE(masize)
ALTER TABLE dbo.TONKHO ADD CONSTRAINT FK_TONKHO_CUAHANG FOREIGN KEY (mach) REFERENCES dbo.CUAHANG(mach)

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG (
    makh INT IDENTITY (1,1) PRIMARY KEY,	
    tenkh NVARCHAR(30) NOT NULL,
    gioitinh BIT NOT NULL,
    ngaysinh DATE NOT NULL,
    diachi NVARCHAR(200),
    email VARCHAR(50) NOT NULL,
    sdt CHAR(10) NOT NULL
);

CREATE TABLE TAIKHOAN (
	id INT IDENTITY (1,1) PRIMARY KEY,
	makh  INT NOT NULL,           --FK KHACHHANG
	email varchar (50) NOT NULL,
	matkhau CHAR(30) NOT NULL,
	quyen VARCHAR(10) CHECK (quyen IN ('admin', 'nhanvien', 'khachhang'))
);

ALTER TABLE dbo.TAIKHOAN ADD CONSTRAINT FK_KHACHHANG FOREIGN KEY (makh) REFERENCES dbo.KHACHHANG(makh)

-- Tạo bảng TRANGTHAI
CREATE TABLE TRANGTHAI (
    matt CHAR(10) PRIMARY KEY CHECK (matt IN ('DVC', 'DDG', 'DGH')),
    tentt NVARCHAR(100) NOT NULL
);

-- Tạo bảng HOADONBAN
CREATE TABLE HOADONBAN (
    mahd INT IDENTITY(1,1) PRIMARY KEY,
    mach CHAR(10) NOT NULL,    --FK CUAHANG
	makh INT NOT NULL,			 --FK KHACHHANG
	httt NVARCHAR(50) NOT NULL , --hình thức thanh toán
	ngaydat DATE NOT NULL,
	matt CHAR(10) NOT NULL CHECK (matt IN ('DVC', 'DDG', 'DGH')) --FK TRANGTHAI
);

ALTER TABLE dbo.HOADONBAN  ADD CONSTRAINT FK_CUAHANG FOREIGN KEY (mach) REFERENCES dbo.CUAHANG(mach)
ALTER TABLE dbo.HOADONBAN  ADD CONSTRAINT FK_NGUOIMUA FOREIGN KEY (makh) REFERENCES dbo.KHACHHANG(makh)
ALTER TABLE dbo.HOADONBAN  ADD CONSTRAINT FK_TRANGTHAIDONHANG FOREIGN KEY (matt) REFERENCES dbo.TRANGTHAI(matt)

-- Tạo bảng CHITIETHOADONBAN
CREATE TABLE CHITIETHOADONBAN (
    mahd INT NOT NULL,   --FK HOADONBAN
    masp CHAR(10) NOT NULL,	 --FK SANPHAM
    soluong INT NOT NULL,
	masize NVARCHAR(10) NOT NULL,
	PRIMARY KEY (mahd, masp)
);

ALTER TABLE dbo.CHITIETHOADONBAN ADD CONSTRAINT FK_HOADONBAN FOREIGN KEY (mahd) REFERENCES dbo.HOADONBAN(mahd)
ALTER TABLE dbo.CHITIETHOADONBAN ADD CONSTRAINT FK_CHITIETSANPHAMBAN FOREIGN KEY (masp) REFERENCES dbo.SANPHAM(masp)

-- Tạo bảng HOADONNHAP
CREATE TABLE HOADONNHAP (
    mahd CHAR(10) PRIMARY KEY,  
    math CHAR(10) NOT NULL,   --FK THUONGHIEU
    ngaynhap DATE NOT NULL,
    tongtientra FLOAT NOT NULL,
	mach CHAR(10) NOT NULL
);

ALTER TABLE dbo.HOADONNHAP ADD CONSTRAINT FK_NHAPTU FOREIGN KEY (math) REFERENCES dbo.THUONGHIEU(math)
ALTER TABLE dbo.HOADONNHAP ADD CONSTRAINT FK_NHAPDEN FOREIGN KEY (mach) REFERENCES dbo.CUAHANG(mach)

-- Tạo bảng CHITIETHOADONNHAP
CREATE TABLE CHITIETHOADONNHAP (
    mahd CHAR(10) NOT NULL,  --FK HOADONNHAP
    masp CHAR(10) NOT NULL,   --FK SANPHAM
    soluong INT NOT NULL,
	masize NVARCHAR(10) NOT NULL,
	PRIMARY KEY (mahd, masp)
);

ALTER TABLE dbo.CHITIETHOADONNHAP ADD CONSTRAINT FK_HOADONNHAP FOREIGN KEY (mahd) REFERENCES dbo.HOADONNHAP(mahd)
ALTER TABLE dbo.CHITIETHOADONNHAP ADD CONSTRAINT FK_SANPHAMNHAP FOREIGN KEY (masp) REFERENCES dbo.SANPHAM(masp)

